// ============================================================================
// FILE: apps/web/components/calendar/CalendarPage.tsx
// Main calendar page — view toggle (month/week/list), filters, KPI summary.
// URL params: ?clientId=&country=&area=&type=&view=month|week|list
// ============================================================================

'use client';

import { useState, useEffect, useCallback } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { MonthView } from './MonthView';
import { WeekView } from './WeekView';
import { ListView } from './ListView';
import { YearView } from './YearView';
import { CalendarSummaryBar, type UrgencyFilter } from './CalendarSummaryBar';
import { EventDrawer } from './EventDrawer';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CalendarEvent {
  readonly id: string;
  readonly type: string;
  readonly title: string;
  readonly date: string;
  readonly daysUntil: number;
  readonly client: { readonly id: string; readonly name: string };
  readonly country: string;
  readonly regulatoryArea: string;
  readonly status: string;
  readonly assignedTo: string | null;
  readonly notes: string | null;
  readonly autoGenerated: boolean;
  readonly previousDate: string | null;
  readonly updateReason: string | null;
}

interface Summary {
  readonly overdue: number;
  readonly dueThisWeek: number;
  readonly dueThisMonth: number;
  readonly byCountry: readonly { country: string; count: number }[];
  readonly byType: readonly { type: string; count: number }[];
}

type ViewMode = 'year' | 'month' | 'week' | 'list';

const API_BASE = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:3000';
const COUNTRIES = ['US', 'EU', 'BR'];
const TYPES = ['DEADLINE', 'FILING', 'AUDIT', 'RENEWAL', 'REGULATORY_CHANGE', 'REVIEW'];
const AREAS = ['Financiero', 'Datos/GDPR', 'Laboral', 'Ambiental', 'Fiscal'];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function CalendarPage() {
  const searchParams = useSearchParams();
  const router = useRouter();

  // Read initial values from URL params
  const [view, setView] = useState<ViewMode>(
    (searchParams.get('view') as ViewMode) || 'month',
  );
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedEvent, setSelectedEvent] = useState<CalendarEvent | null>(null);
  const [urgencyFilter, setUrgencyFilter] = useState<UrgencyFilter>('all');

  // Filters from URL params
  const [filterClientId, setFilterClientId] = useState(searchParams.get('clientId') ?? '');
  const [filterCountry, setFilterCountry] = useState(searchParams.get('country') ?? '');
  const [filterArea, setFilterArea] = useState(searchParams.get('area') ?? '');
  const [filterType, setFilterType] = useState(searchParams.get('type') ?? '');

  // Sync URL params
  useEffect(() => {
    const params = new URLSearchParams();
    if (view !== 'month') params.set('view', view);
    if (filterClientId) params.set('clientId', filterClientId);
    if (filterCountry) params.set('country', filterCountry);
    if (filterArea) params.set('area', filterArea);
    if (filterType) params.set('type', filterType);
    const qs = params.toString();
    router.replace(qs ? `?${qs}` : '/calendar', { scroll: false });
  }, [view, filterClientId, filterCountry, filterArea, filterType, router]);

  const fetchData = useCallback(async () => {
    try {
      const token = sessionStorage.getItem('auth_token') ?? process.env['NEXT_PUBLIC_DEV_TOKEN'] ?? null;
      const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {};

      const qs = new URLSearchParams();
      if (filterClientId) qs.set('clientId', filterClientId);
      if (filterCountry) qs.set('country', filterCountry);
      if (filterArea) qs.set('area', filterArea);
      if (filterType) qs.set('type', filterType);

      const [eventsRes, summaryRes] = await Promise.all([
        fetch(`${API_BASE}/api/calendar/events?${qs}`, { headers }),
        fetch(`${API_BASE}/api/calendar/summary`, { headers }),
      ]);

      if (eventsRes.ok) {
        const data = await eventsRes.json();
        setEvents(data.data ?? []);
      }
      if (summaryRes.ok) {
        setSummary(await summaryRes.json());
      }
    } catch {
      // Keep current state on error
    } finally {
      setLoading(false);
    }
  }, [filterClientId, filterCountry, filterArea, filterType]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const handleStatusChange = async (eventId: string, status: string) => {
    try {
      const token = sessionStorage.getItem('auth_token') ?? process.env['NEXT_PUBLIC_DEV_TOKEN'] ?? null;
      const res = await fetch(`${API_BASE}/api/calendar/events/${eventId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ status }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({ message: `HTTP ${res.status}` }));
        console.error('Calendar status change failed:', err);
      }
    } catch (err) {
      console.error('Calendar status change error:', err);
    }
    fetchData();
    setSelectedEvent(null);
  };

  const handleAssign = async (eventId: string, assignedTo: string) => {
    try {
      const token = sessionStorage.getItem('auth_token') ?? process.env['NEXT_PUBLIC_DEV_TOKEN'] ?? null;
      await fetch(`${API_BASE}/api/calendar/events/${eventId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ assignedTo }),
      });
    } catch (err) {
      console.error('Calendar assign error:', err);
    }
    fetchData();
  };

  const handleExport = () => {
    const qs = new URLSearchParams();
    if (filterClientId) qs.set('clientId', filterClientId);
    if (filterCountry) qs.set('country', filterCountry);
    window.open(`${API_BASE}/api/calendar/export/ical?${qs}`, '_blank');
  };

  // Count total upcoming (next 90 days)
  const totalUpcoming = events.filter((e) => e.status !== 'COMPLETED' && e.daysUntil >= 0).length;

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Calendario de Compliance</h1>
          <p className="text-sm text-gray-500 mt-1">Obligaciones, vencimientos y eventos regulatorios</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={handleExport} className="btn-secondary text-xs flex items-center gap-1.5">
            Exportar .ics
          </button>
        </div>
      </div>

      {/* Summary KPIs */}
      {summary && (
        <CalendarSummaryBar
          summary={summary}
          totalUpcoming={totalUpcoming}
          activeFilter={urgencyFilter}
          onFilterClick={(filter) => {
            setUrgencyFilter(filter);
            if (filter !== 'all' && view !== 'list') setView('list');
          }}
        />
      )}

      {/* Filters + view toggle */}
      <div className="card card-body">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3 flex-wrap">
            {/* Client filter */}
            <input
              type="text"
              value={filterClientId}
              onChange={(e) => setFilterClientId(e.target.value)}
              placeholder="ID de cliente..."
              className="input w-auto text-xs"
              style={{ maxWidth: '160px' }}
            />

            {/* Country filter */}
            <select
              value={filterCountry}
              onChange={(e) => setFilterCountry(e.target.value)}
              className="input w-auto text-xs"
            >
              <option value="">Todos los paises</option>
              {COUNTRIES.map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>

            {/* Area filter */}
            <select
              value={filterArea}
              onChange={(e) => setFilterArea(e.target.value)}
              className="input w-auto text-xs"
            >
              <option value="">Todas las areas</option>
              {AREAS.map((a) => (
                <option key={a} value={a}>{a}</option>
              ))}
            </select>

            {/* Type filter */}
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="input w-auto text-xs"
            >
              <option value="">Todos los tipos</option>
              {TYPES.map((t) => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
          </div>

          {/* View toggle */}
          <div className="flex items-center bg-gray-100 rounded-lg p-0.5">
            {(['year', 'month', 'week', 'list'] as const).map((v) => (
              <button
                key={v}
                onClick={() => { setView(v); if (v !== 'list') setUrgencyFilter('all'); }}
                className={`text-xs px-3 py-1.5 rounded-md transition-colors ${
                  view === v ? 'bg-white shadow-sm text-brand-700 font-medium' : 'text-gray-500'
                }`}
              >
                {v === 'year' ? 'Anual' : v === 'month' ? 'Mensual' : v === 'week' ? 'Semanal' : 'Lista'}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Calendar view */}
      {loading ? (
        <div className="card card-body flex items-center justify-center h-64">
          <div className="flex items-center gap-2 text-sm text-gray-400">
            <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Cargando calendario...
          </div>
        </div>
      ) : view === 'year' ? (
        <YearView events={events} onEventClick={setSelectedEvent} />
      ) : view === 'month' ? (
        <MonthView events={events} onEventClick={setSelectedEvent} />
      ) : view === 'week' ? (
        <WeekView events={events} onEventClick={setSelectedEvent} />
      ) : (
        <ListView
          events={events}
          onEventClick={setSelectedEvent}
          onStatusChange={handleStatusChange}
          onAssign={handleAssign}
          activeFilter={urgencyFilter}
        />
      )}

      {/* Event detail drawer */}
      {selectedEvent && (
        <EventDrawer
          event={selectedEvent}
          onClose={() => setSelectedEvent(null)}
          onStatusChange={handleStatusChange}
        />
      )}
    </div>
  );
}
