// ============================================================================
// FILE: apps/web/components/calendar/CalendarPage.tsx
// Main calendar page — view toggle, filters, KPI summary, calendar/list.
// ============================================================================

'use client';

import { useState, useEffect, useCallback } from 'react';
import { MonthView } from './MonthView';
import { ListView } from './ListView';
import { CalendarSummaryBar } from './CalendarSummaryBar';
import { EventDrawer } from './EventDrawer';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CalendarEvent {
  readonly id: string;
  readonly type: string;
  readonly title: string;
  readonly date: string;
  readonly daysUntil: number;
  readonly client: { readonly id: string; readonly name: string };
  readonly country: string;
  readonly regulatoryArea: string;
  readonly status: string;
  readonly assignedTo: string | null;
  readonly notes: string | null;
  readonly autoGenerated: boolean;
  readonly previousDate: string | null;
  readonly updateReason: string | null;
}

interface Summary {
  readonly overdue: number;
  readonly dueThisWeek: number;
  readonly dueThisMonth: number;
  readonly byCountry: readonly { country: string; count: number }[];
  readonly byType: readonly { type: string; count: number }[];
}

type ViewMode = 'month' | 'list';

const API_BASE = process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:3000';

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function CalendarPage() {
  const [view, setView] = useState<ViewMode>('month');
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedEvent, setSelectedEvent] = useState<CalendarEvent | null>(null);

  // Filters
  const [filterCountry, setFilterCountry] = useState('');
  const [filterType, setFilterType] = useState('');

  const fetchData = useCallback(async () => {
    try {
      const token = sessionStorage.getItem('auth_token');
      const headers: Record<string, string> = token ? { Authorization: `Bearer ${token}` } : {};

      const qs = new URLSearchParams();
      if (filterCountry) qs.set('country', filterCountry);
      if (filterType) qs.set('type', filterType);

      const [eventsRes, summaryRes] = await Promise.all([
        fetch(`${API_BASE}/api/calendar/events?${qs}`, { headers }),
        fetch(`${API_BASE}/api/calendar/summary`, { headers }),
      ]);

      if (eventsRes.ok) {
        const data = await eventsRes.json();
        setEvents(data.data ?? []);
      }
      if (summaryRes.ok) {
        setSummary(await summaryRes.json());
      }
    } catch {
      // Keep current state on error
    } finally {
      setLoading(false);
    }
  }, [filterCountry, filterType]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const handleStatusChange = async (eventId: string, status: string) => {
    const token = sessionStorage.getItem('auth_token');
    await fetch(`${API_BASE}/api/calendar/events/${eventId}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({ status }),
    });
    fetchData();
    setSelectedEvent(null);
  };

  const handleExport = () => {
    const qs = new URLSearchParams();
    if (filterCountry) qs.set('country', filterCountry);
    window.open(`${API_BASE}/api/calendar/export/ical?${qs}`, '_blank');
  };

  const COUNTRIES = ['', 'US', 'EU', 'ES', 'MX', 'AR', 'BR'];
  const TYPES = ['', 'DEADLINE', 'FILING', 'AUDIT', 'RENEWAL', 'REGULATORY_CHANGE', 'REVIEW'];

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Calendario de Compliance</h1>
          <p className="text-sm text-gray-500 mt-1">Obligaciones, vencimientos y eventos regulatorios</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={handleExport} className="btn-secondary text-xs flex items-center gap-1.5">
            Exportar .ics
          </button>
        </div>
      </div>

      {/* Summary KPIs */}
      {summary && <CalendarSummaryBar summary={summary} />}

      {/* Filters + view toggle */}
      <div className="card card-body">
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3">
            {/* Country filter */}
            <select
              value={filterCountry}
              onChange={(e) => setFilterCountry(e.target.value)}
              className="input w-auto text-xs"
            >
              <option value="">Todos los países</option>
              {COUNTRIES.filter(Boolean).map((c) => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>

            {/* Type filter */}
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="input w-auto text-xs"
            >
              <option value="">Todos los tipos</option>
              {TYPES.filter(Boolean).map((t) => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
          </div>

          {/* View toggle */}
          <div className="flex items-center bg-gray-100 rounded-lg p-0.5">
            <button
              onClick={() => setView('month')}
              className={`text-xs px-3 py-1.5 rounded-md transition-colors ${
                view === 'month' ? 'bg-white shadow-sm text-brand-700 font-medium' : 'text-gray-500'
              }`}
            >
              Mensual
            </button>
            <button
              onClick={() => setView('list')}
              className={`text-xs px-3 py-1.5 rounded-md transition-colors ${
                view === 'list' ? 'bg-white shadow-sm text-brand-700 font-medium' : 'text-gray-500'
              }`}
            >
              Lista
            </button>
          </div>
        </div>
      </div>

      {/* Calendar view */}
      {loading ? (
        <div className="card card-body flex items-center justify-center h-64">
          <div className="flex items-center gap-2 text-sm text-gray-400">
            <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            Cargando calendario...
          </div>
        </div>
      ) : view === 'month' ? (
        <MonthView events={events} onEventClick={setSelectedEvent} />
      ) : (
        <ListView events={events} onEventClick={setSelectedEvent} onStatusChange={handleStatusChange} />
      )}

      {/* Event detail drawer */}
      {selectedEvent && (
        <EventDrawer
          event={selectedEvent}
          onClose={() => setSelectedEvent(null)}
          onStatusChange={handleStatusChange}
        />
      )}
    </div>
  );
}
