// ============================================================================
// FILE: apps/api/src/services/calendarService.ts
// CalendarService — auto-generates and manages calendar events from the
// ingestion pipeline, OnboardingEngine, and ImpactAnalyzerAgent.
// ============================================================================

import { randomUUID } from 'node:crypto';
import type {
  CalendarEvent,
  CalendarEventType,
  CalendarSummary,
} from '@regwatch/shared';
import { createServiceLogger } from '../config/logger.js';

const logger = createServiceLogger('service:calendar');

// ---------------------------------------------------------------------------
// In-memory store (PostgreSQL in production)
// ---------------------------------------------------------------------------

const eventsStore: Map<string, CalendarEvent> = new Map();

// ---------------------------------------------------------------------------
// Input types
// ---------------------------------------------------------------------------

export interface CreateFromObligationParams {
  readonly obligationId: string;
  readonly obligationName: string;
  readonly clientId: string;
  readonly clientName: string;
  readonly country: string;
  readonly regulatoryArea: string;
  readonly dueDate: string;
}

export interface UpdateDeadlineParams {
  readonly obligationId: string;
  readonly newDeadline: string;
  readonly oldDeadline: string;
  readonly regulationTitle: string;
}

export interface CreateFromRegulationParams {
  readonly regulationId: string;
  readonly regulationTitle: string;
  readonly effectiveDate: string;
  readonly country: string;
  readonly regulatoryArea: string;
}

export interface CreateEventInput {
  readonly type: CalendarEventType;
  readonly title: string;
  readonly date: string;
  readonly client: { readonly id: string; readonly name: string };
  readonly country: string;
  readonly regulatoryArea: string;
  readonly obligationId?: string;
  readonly regulatoryChangeId?: string;
  readonly assignedTo?: string;
  readonly notes?: string;
  readonly autoGenerated: boolean;
}

export interface EventFilters {
  readonly from?: string;
  readonly to?: string;
  readonly clientId?: string;
  readonly country?: string;
  readonly area?: string;
  readonly type?: CalendarEventType;
}

// ---------------------------------------------------------------------------
// CalendarService
// ---------------------------------------------------------------------------

export class CalendarService {
  /**
   * Case A: OnboardingEngine creates a Deadline node in Neo4j.
   * Auto-generates a DEADLINE calendar event.
   */
  createEventFromObligation(params: CreateFromObligationParams): CalendarEvent {
    const requestId = randomUUID();
    const startTime = Date.now();

    const event = this.createEvent({
      type: 'DEADLINE',
      title: `${params.obligationName} — ${params.clientName}`,
      date: params.dueDate,
      client: { id: params.clientId, name: params.clientName },
      country: params.country,
      regulatoryArea: params.regulatoryArea,
      obligationId: params.obligationId,
      autoGenerated: true,
    });

    logger.info({
      service: 'calendar',
      operation: 'create_from_obligation',
      requestId,
      obligationId: params.obligationId,
      eventId: event.id,
      clientId: params.clientId,
      duration: Date.now() - startTime,
      result: 'success',
    });

    return event;
  }

  /**
   * Case B: ImpactAnalyzer detects a shortened deadline.
   * Updates existing event or creates one if not found.
   */
  updateEventDeadline(params: UpdateDeadlineParams): CalendarEvent | null {
    const requestId = randomUUID();
    const startTime = Date.now();

    // Find event by obligationId
    const existing = Array.from(eventsStore.values()).find(
      (e) => e.obligationId === params.obligationId,
    );

    if (!existing) {
      logger.warn({
        service: 'calendar',
        operation: 'update_deadline',
        requestId,
        obligationId: params.obligationId,
        result: 'not_found',
        duration: Date.now() - startTime,
      });
      return null;
    }

    const updated: CalendarEvent = {
      ...existing,
      date: params.newDeadline,
      daysUntil: daysUntilDate(params.newDeadline),
      previousDate: params.oldDeadline,
      updateReason: params.regulationTitle,
    };

    eventsStore.set(existing.id, updated);

    logger.info({
      service: 'calendar',
      operation: 'update_deadline',
      requestId,
      eventId: existing.id,
      obligationId: params.obligationId,
      oldDeadline: params.oldDeadline,
      newDeadline: params.newDeadline,
      duration: Date.now() - startTime,
      result: 'success',
    });

    return updated;
  }

  /**
   * Case C: New regulation with future effective date.
   * Creates a REGULATORY_CHANGE event.
   */
  createEventFromRegulation(params: CreateFromRegulationParams): CalendarEvent {
    const requestId = randomUUID();
    const startTime = Date.now();

    const event = this.createEvent({
      type: 'REGULATORY_CHANGE',
      title: `Vigencia: ${params.regulationTitle}`,
      date: params.effectiveDate,
      client: { id: 'all', name: 'Todos los clientes' },
      country: params.country,
      regulatoryArea: params.regulatoryArea,
      regulatoryChangeId: params.regulationId,
      autoGenerated: true,
    });

    logger.info({
      service: 'calendar',
      operation: 'create_from_regulation',
      requestId,
      regulationId: params.regulationId,
      eventId: event.id,
      effectiveDate: params.effectiveDate,
      duration: Date.now() - startTime,
      result: 'success',
    });

    return event;
  }

  /**
   * Generic event creation.
   */
  createEvent(input: CreateEventInput): CalendarEvent {
    const event: CalendarEvent = {
      id: randomUUID(),
      type: input.type,
      title: input.title,
      date: input.date,
      daysUntil: daysUntilDate(input.date),
      client: input.client,
      country: input.country,
      regulatoryArea: input.regulatoryArea,
      obligationId: input.obligationId ?? null,
      regulatoryChangeId: input.regulatoryChangeId ?? null,
      status: 'PENDING',
      assignedTo: input.assignedTo ?? null,
      notes: input.notes ?? null,
      autoGenerated: input.autoGenerated,
      previousDate: null,
      updateReason: null,
    };

    eventsStore.set(event.id, event);
    return event;
  }

  /**
   * Generic event update.
   */
  updateEvent(
    eventId: string,
    updates: Partial<Pick<CalendarEvent, 'status' | 'assignedTo' | 'notes' | 'date'>>,
  ): CalendarEvent | null {
    const event = eventsStore.get(eventId);
    if (!event) return null;

    const updated: CalendarEvent = {
      ...event,
      ...(updates.status ? { status: updates.status } : {}),
      ...(updates.assignedTo !== undefined ? { assignedTo: updates.assignedTo } : {}),
      ...(updates.notes !== undefined ? { notes: updates.notes } : {}),
      ...(updates.date ? {
        date: updates.date,
        daysUntil: daysUntilDate(updates.date),
        previousDate: event.date,
      } : {}),
    };

    eventsStore.set(eventId, updated);
    return updated;
  }

  /**
   * Query events with filters.
   */
  getEvents(filters: EventFilters = {}): CalendarEvent[] {
    let events = Array.from(eventsStore.values());

    if (filters.from) events = events.filter((e) => e.date >= filters.from!);
    if (filters.to) events = events.filter((e) => e.date <= filters.to!);
    if (filters.clientId) events = events.filter((e) => e.client.id === filters.clientId);
    if (filters.country) events = events.filter((e) => e.country === filters.country);
    if (filters.area) events = events.filter((e) => e.regulatoryArea === filters.area);
    if (filters.type) events = events.filter((e) => e.type === filters.type);

    return events.map((e) => ({ ...e, daysUntil: daysUntilDate(e.date) }));
  }

  /**
   * Summary counts for KPI cards.
   */
  getSummary(): CalendarSummary {
    const events = Array.from(eventsStore.values())
      .filter((e) => e.status !== 'COMPLETED')
      .map((e) => ({ ...e, daysUntil: daysUntilDate(e.date) }));

    const now = todayStr();
    const weekEnd = dateOffset(7);
    const monthEnd = dateOffset(30);

    const overdue = events.filter((e) => e.date < now).length;
    const dueThisWeek = events.filter((e) => e.date >= now && e.date <= weekEnd).length;
    const dueThisMonth = events.filter((e) => e.date >= now && e.date <= monthEnd).length;

    const countryMap = new Map<string, number>();
    for (const e of events) {
      countryMap.set(e.country, (countryMap.get(e.country) ?? 0) + 1);
    }
    const byCountry = Array.from(countryMap.entries()).map(([country, count]) => ({ country, count }));

    const typeMap = new Map<CalendarEventType, number>();
    for (const e of events) {
      typeMap.set(e.type as CalendarEventType, (typeMap.get(e.type as CalendarEventType) ?? 0) + 1);
    }
    const byType = Array.from(typeMap.entries()).map(([type, count]) => ({ type, count }));

    return { overdue, dueThisWeek, dueThisMonth, byCountry, byType };
  }

  /**
   * Get the underlying store (for deadline notifier and other internal services).
   */
  getAllEvents(): CalendarEvent[] {
    return Array.from(eventsStore.values());
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function todayStr(): string {
  return new Date().toISOString().split('T')[0]!;
}

function dateOffset(days: number): string {
  return new Date(Date.now() + days * 86_400_000).toISOString().split('T')[0]!;
}

function daysUntilDate(dateStr: string): number {
  const target = new Date(dateStr).getTime();
  const now = new Date(todayStr()).getTime();
  return Math.ceil((target - now) / 86_400_000);
}
