// ============================================================================
// FILE: apps/api/src/services/calendarService.ts
// CalendarService — auto-generates and manages calendar events from the
// ingestion pipeline, OnboardingEngine, and ImpactAnalyzerAgent.
// Backed by PostgreSQL via Prisma (obligations table).
// ============================================================================

import { randomUUID } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import type {
  CalendarEvent,
  CalendarEventType,
  CalendarEventStatus,
  CalendarSummary,
} from '@regwatch/shared';
import { createServiceLogger } from '../config/logger.js';

const logger = createServiceLogger('service:calendar');

// ---------------------------------------------------------------------------
// Input types
// ---------------------------------------------------------------------------

export interface CreateFromObligationParams {
  readonly obligationId: string;
  readonly obligationName: string;
  readonly clientId: string;
  readonly clientName: string;
  readonly country: string;
  readonly regulatoryArea: string;
  readonly dueDate: string;
  readonly tenantId: string;
  readonly changeId: string;
}

export interface UpdateDeadlineParams {
  readonly obligationId: string;
  readonly newDeadline: string;
  readonly oldDeadline: string;
  readonly regulationTitle: string;
}

export interface CreateFromRegulationParams {
  readonly regulationId: string;
  readonly regulationTitle: string;
  readonly effectiveDate: string;
  readonly country: string;
  readonly regulatoryArea: string;
}

export interface CreateEventInput {
  readonly type: CalendarEventType;
  readonly title: string;
  readonly date: string;
  readonly client: { readonly id: string; readonly name: string };
  readonly country: string;
  readonly regulatoryArea: string;
  readonly tenantId: string;
  readonly changeId: string;
  readonly obligationId?: string;
  readonly regulatoryChangeId?: string;
  readonly assignedTo?: string;
  readonly notes?: string;
  readonly autoGenerated: boolean;
}

export interface EventFilters {
  readonly from?: string;
  readonly to?: string;
  readonly clientId?: string;
  readonly country?: string;
  readonly area?: string;
  readonly type?: CalendarEventType;
}

// ---------------------------------------------------------------------------
// CalendarService — PostgreSQL-backed via Prisma
// ---------------------------------------------------------------------------

export class CalendarService {
  private readonly prisma: PrismaClient;

  constructor(prisma: PrismaClient) {
    this.prisma = prisma;
  }

  /**
   * Case A: OnboardingEngine creates a Deadline node in Neo4j.
   * Auto-generates a DEADLINE calendar event persisted as an obligation.
   */
  async createEventFromObligation(params: CreateFromObligationParams): Promise<CalendarEvent> {
    const requestId = randomUUID();
    const startTime = Date.now();

    // Check if obligation already exists to avoid duplicates
    const existing = await this.prisma.obligation.findUnique({
      where: { id: params.obligationId },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });

    if (existing) {
      logger.info({
        service: 'calendar',
        operation: 'create_from_obligation',
        requestId,
        obligationId: params.obligationId,
        duration: Date.now() - startTime,
        result: 'already_exists',
      });
      return obligationToEvent(existing);
    }

    const obligation = await this.prisma.obligation.create({
      data: {
        id: params.obligationId,
        clientId: params.clientId,
        tenantId: params.tenantId,
        changeId: params.changeId,
        title: `${params.obligationName} — ${params.clientName}`,
        description: `Auto-generated from obligation: ${params.regulatoryArea}`,
        deadline: new Date(params.dueDate),
        status: 'PENDING',
        priority: 'MEDIUM',
      },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });

    const event = obligationToEvent(obligation);

    logger.info({
      service: 'calendar',
      operation: 'create_from_obligation',
      requestId,
      obligationId: params.obligationId,
      eventId: event.id,
      clientId: params.clientId,
      duration: Date.now() - startTime,
      result: 'success',
    });

    return event;
  }

  /**
   * Case B: ImpactAnalyzer detects a shortened deadline.
   * Updates existing obligation deadline in PostgreSQL.
   */
  async updateEventDeadline(params: UpdateDeadlineParams): Promise<CalendarEvent | null> {
    const requestId = randomUUID();
    const startTime = Date.now();

    const existing = await this.prisma.obligation.findUnique({
      where: { id: params.obligationId },
    });

    if (!existing) {
      logger.warn({
        service: 'calendar',
        operation: 'update_deadline',
        requestId,
        obligationId: params.obligationId,
        result: 'not_found',
        duration: Date.now() - startTime,
      });
      return null;
    }

    const updated = await this.prisma.obligation.update({
      where: { id: params.obligationId },
      data: {
        deadline: new Date(params.newDeadline),
        description: `Deadline changed: ${params.oldDeadline} → ${params.newDeadline} (${params.regulationTitle})`,
      },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });

    const event: CalendarEvent = {
      ...obligationToEvent(updated),
      previousDate: params.oldDeadline,
      updateReason: params.regulationTitle,
    };

    logger.info({
      service: 'calendar',
      operation: 'update_deadline',
      requestId,
      eventId: existing.id,
      obligationId: params.obligationId,
      oldDeadline: params.oldDeadline,
      newDeadline: params.newDeadline,
      duration: Date.now() - startTime,
      result: 'success',
    });

    return event;
  }

  /**
   * Case C: New regulation with future effective date.
   * Creates a REGULATORY_CHANGE event stored as an obligation for tracking.
   */
  async createEventFromRegulation(params: CreateFromRegulationParams): Promise<CalendarEvent | null> {
    const requestId = randomUUID();
    const startTime = Date.now();

    // Need a client and change reference for the obligation
    const client = await this.prisma.client.findFirst();
    const change = await this.prisma.regulatoryChange.findUnique({
      where: { id: params.regulationId },
    });

    if (!client || !change) {
      logger.warn({
        service: 'calendar',
        operation: 'create_from_regulation',
        requestId,
        regulationId: params.regulationId,
        result: 'missing_references',
        duration: Date.now() - startTime,
      });
      return null;
    }

    const obligation = await this.prisma.obligation.create({
      data: {
        clientId: client.id,
        tenantId: client.tenantId,
        changeId: change.id,
        title: `Vigencia: ${params.regulationTitle}`,
        description: `Regulatory change effective date — ${params.regulatoryArea}`,
        deadline: new Date(params.effectiveDate),
        status: 'PENDING',
        priority: 'MEDIUM',
      },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });

    const event = obligationToEvent(obligation);

    logger.info({
      service: 'calendar',
      operation: 'create_from_regulation',
      requestId,
      regulationId: params.regulationId,
      eventId: event.id,
      effectiveDate: params.effectiveDate,
      duration: Date.now() - startTime,
      result: 'success',
    });

    return event;
  }

  /**
   * Generic event creation (stores as obligation in PostgreSQL).
   */
  async createEvent(input: CreateEventInput): Promise<CalendarEvent> {
    const obligation = await this.prisma.obligation.create({
      data: {
        clientId: input.client.id,
        tenantId: input.tenantId,
        changeId: input.changeId,
        title: input.title,
        description: input.notes ?? '',
        deadline: new Date(input.date),
        status: 'PENDING',
        priority: 'MEDIUM',
        assignedTo: input.assignedTo ?? '',
      },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });

    return obligationToEvent(obligation);
  }

  /**
   * Generic event update (updates obligation in PostgreSQL).
   */
  async updateEvent(
    eventId: string,
    updates: Partial<Pick<CalendarEvent, 'status' | 'assignedTo' | 'notes' | 'date'>>,
  ): Promise<CalendarEvent | null> {
    const existing = await this.prisma.obligation.findUnique({ where: { id: eventId } });
    if (!existing) return null;

    const data: Record<string, unknown> = {};
    if (updates.status) data['status'] = mapCalendarStatusToObligation(updates.status);
    if (updates.assignedTo !== undefined) data['assignedTo'] = updates.assignedTo ?? '';
    if (updates.notes !== undefined) data['description'] = updates.notes ?? '';
    if (updates.date) data['deadline'] = new Date(updates.date);

    const updated = await this.prisma.obligation.update({
      where: { id: eventId },
      data,
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });

    return obligationToEvent(updated);
  }

  /**
   * Query events with filters (reads obligations from PostgreSQL).
   */
  async getEvents(filters: EventFilters = {}): Promise<CalendarEvent[]> {
    const where: Record<string, unknown> = {};

    if (filters.clientId) where['clientId'] = filters.clientId;
    if (filters.from || filters.to) {
      const deadlineFilter: Record<string, Date> = {};
      if (filters.from) deadlineFilter['gte'] = new Date(filters.from);
      if (filters.to) deadlineFilter['lte'] = new Date(filters.to);
      where['deadline'] = deadlineFilter;
    }

    const obligations = await this.prisma.obligation.findMany({
      where,
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
      orderBy: { deadline: 'asc' },
      take: 200,
    });

    let events = obligations.map(obligationToEvent);

    if (filters.country) events = events.filter((e) => e.country === filters.country);
    if (filters.area) events = events.filter((e) => e.regulatoryArea === filters.area);

    return events;
  }

  /**
   * Summary counts for KPI cards (reads from PostgreSQL).
   */
  async getSummary(): Promise<CalendarSummary> {
    const obligations = await this.prisma.obligation.findMany({
      where: { status: { not: 'COMPLETED' } },
      include: {
        change: { select: { country: true } },
      },
    });

    const now = todayStr();
    const weekEnd = dateOffset(7);
    const monthEnd = dateOffset(30);

    const events = obligations.map((o) => ({
      date: o.deadline.toISOString().split('T')[0]!,
      country: o.change.country,
      type: 'DEADLINE' as CalendarEventType,
    }));

    const overdue = events.filter((e) => e.date < now).length;
    const dueThisWeek = events.filter((e) => e.date >= now && e.date <= weekEnd).length;
    const dueThisMonth = events.filter((e) => e.date >= now && e.date <= monthEnd).length;

    const countryMap = new Map<string, number>();
    for (const e of events) {
      countryMap.set(e.country, (countryMap.get(e.country) ?? 0) + 1);
    }
    const byCountry = Array.from(countryMap.entries()).map(([country, count]) => ({ country, count }));

    const typeMap = new Map<CalendarEventType, number>();
    for (const e of events) {
      typeMap.set(e.type, (typeMap.get(e.type) ?? 0) + 1);
    }
    const byType = Array.from(typeMap.entries()).map(([type, count]) => ({ type, count }));

    return { overdue, dueThisWeek, dueThisMonth, byCountry, byType };
  }

  /**
   * Get all events (for deadline notifier and other internal services).
   * Reads all non-completed obligations from PostgreSQL.
   */
  async getAllEvents(): Promise<CalendarEvent[]> {
    const obligations = await this.prisma.obligation.findMany({
      where: { status: { not: 'COMPLETED' } },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
      orderBy: { deadline: 'asc' },
    });

    return obligations.map(obligationToEvent);
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function todayStr(): string {
  return new Date().toISOString().split('T')[0]!;
}

function dateOffset(days: number): string {
  return new Date(Date.now() + days * 86_400_000).toISOString().split('T')[0]!;
}

function daysUntilDate(dateStr: string): number {
  const target = new Date(dateStr).getTime();
  const now = new Date(todayStr()).getTime();
  return Math.ceil((target - now) / 86_400_000);
}

/** Map obligation status to CalendarEventStatus. */
function mapObligationStatus(status: string, dateStr: string): CalendarEventStatus {
  if (status === 'COMPLETED') return 'COMPLETED';
  if (status === 'IN_PROGRESS') return 'IN_PROGRESS';
  if (status === 'OVERDUE' || dateStr < todayStr()) return 'OVERDUE';
  return 'PENDING';
}

/** Map CalendarEventStatus back to obligation status for updates. */
function mapCalendarStatusToObligation(status: CalendarEventStatus): string {
  switch (status) {
    case 'COMPLETED': return 'COMPLETED';
    case 'IN_PROGRESS': return 'IN_PROGRESS';
    case 'OVERDUE': return 'OVERDUE';
    case 'PENDING': return 'PENDING';
    default: return 'PENDING';
  }
}

/** Map affected area to display name. */
function mapArea(area: string): string {
  const mapping: Record<string, string> = {
    'securities': 'Financiero', 'banking': 'Financiero', 'digital-finance': 'Financiero',
    'corporate': 'Financiero', 'insurance': 'Financiero', 'disclosure': 'Financiero',
    'data-protection': 'Datos/GDPR',
    'labor': 'Laboral',
    'environmental': 'Ambiental', 'climate': 'Ambiental', 'energy': 'Ambiental',
    'fiscal': 'Fiscal', 'international-tax': 'Fiscal',
    'sustainability': 'Sostenibilidad',
    'aml': 'Financiero', 'compliance': 'Financiero',
    'payments': 'Financiero', 'technology': 'Tecnologia',
    'trade': 'Comercio Exterior',
  };
  return mapping[area] ?? area;
}

/** Convert a Prisma obligation (with includes) to a CalendarEvent. */
function obligationToEvent(obligation: {
  id: string;
  title: string;
  deadline: Date;
  status: string;
  assignedTo: string;
  description: string;
  changeId: string;
  client: { id: string; name: string };
  change: { country: string; affectedAreas: string[] };
}): CalendarEvent {
  const dateStr = obligation.deadline.toISOString().split('T')[0]!;
  const areas = obligation.change.affectedAreas;

  return {
    id: obligation.id,
    type: 'DEADLINE' as CalendarEventType,
    title: obligation.title,
    date: dateStr,
    daysUntil: daysUntilDate(dateStr),
    client: { id: obligation.client.id, name: obligation.client.name },
    country: obligation.change.country,
    regulatoryArea: mapArea(areas[0] ?? 'regulatory'),
    obligationId: obligation.id,
    regulatoryChangeId: obligation.changeId,
    status: mapObligationStatus(obligation.status, dateStr),
    assignedTo: obligation.assignedTo || null,
    notes: obligation.description || null,
    autoGenerated: true,
    previousDate: null,
    updateReason: null,
  };
}
