// ============================================================================
// FILE: apps/api/src/routes/calendar.ts
// Compliance Calendar — reads real obligations from PostgreSQL.
// ============================================================================

import { Router, type Request, type Response } from 'express';
import { randomUUID } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import { Errors } from '@regwatch/shared';
import type {
  CalendarEvent,
  CalendarEventType,
  CalendarEventStatus,
  CalendarSummary,
} from '@regwatch/shared';
import { createServiceLogger } from '../config/logger.js';

const logger = createServiceLogger('route:calendar');

// ---------------------------------------------------------------------------
// Dependencies
// ---------------------------------------------------------------------------

export interface CalendarRouteDeps {
  readonly prisma: PrismaClient;
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

export function createCalendarRouter(deps: CalendarRouteDeps): Router {
  const router = Router();

  // -----------------------------------------------------------------------
  // GET /calendar/events — from real obligations in DB
  // -----------------------------------------------------------------------
  router.get('/calendar/events', async (req: Request, res: Response) => {
    const requestId = req.requestId ?? randomUUID();
    const from = req.query['from'] as string | undefined;
    const to = req.query['to'] as string | undefined;
    const clientId = req.query['clientId'] as string | undefined;
    const country = req.query['country'] as string | undefined;

    const where: Record<string, unknown> = {};
    if (clientId) where['clientId'] = clientId;
    if (from || to) {
      const deadlineFilter: Record<string, Date> = {};
      if (from) deadlineFilter['gte'] = new Date(from);
      if (to) deadlineFilter['lte'] = new Date(to);
      where['deadline'] = deadlineFilter;
    }

    const obligations = await deps.prisma.obligation.findMany({
      where,
      include: {
        client: { select: { id: true, name: true, countries: true } },
        change: { select: { id: true, title: true, country: true, affectedAreas: true } },
      },
      orderBy: { deadline: 'asc' },
      take: 100,
    });

    let events: CalendarEvent[] = obligations.map((o) => {
      const dateStr = o.deadline.toISOString().split('T')[0]!;
      const changeCountry = o.change.country;
      const areas = o.change.affectedAreas as string[];

      return {
        id: o.id,
        type: 'DEADLINE' as CalendarEventType,
        title: o.title,
        date: dateStr,
        daysUntil: daysUntilDate(dateStr),
        client: { id: o.client.id, name: o.client.name },
        country: changeCountry,
        regulatoryArea: mapArea(areas[0] ?? 'regulatory'),
        obligationId: o.id,
        regulatoryChangeId: o.changeId,
        status: mapObligationStatus(o.status, dateStr),
        assignedTo: o.assignedTo || null,
        notes: o.description || null,
        autoGenerated: true,
        previousDate: null,
        updateReason: null,
      };
    });

    if (country) events = events.filter((e) => e.country === country);

    logger.info({ operation: 'calendar:list', requestId, count: events.length });
    res.json({ data: events, total: events.length });
  });

  // -----------------------------------------------------------------------
  // GET /calendar/events/upcoming — next N days
  // -----------------------------------------------------------------------
  router.get('/calendar/events/upcoming', async (req: Request, res: Response) => {
    const days = parseInt(req.query['days'] as string ?? '90', 10);
    const clientId = req.query['clientId'] as string | undefined;
    const cutoff = new Date(Date.now() + days * 86_400_000);

    const where: Record<string, unknown> = {
      deadline: { lte: cutoff },
      status: { not: 'COMPLETED' },
    };
    if (clientId) where['clientId'] = clientId;

    const obligations = await deps.prisma.obligation.findMany({
      where,
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
      orderBy: { deadline: 'asc' },
      take: 50,
    });

    const events: CalendarEvent[] = obligations.map((o) => {
      const dateStr = o.deadline.toISOString().split('T')[0]!;
      return {
        id: o.id,
        type: 'DEADLINE' as CalendarEventType,
        title: o.title,
        date: dateStr,
        daysUntil: daysUntilDate(dateStr),
        client: { id: o.client.id, name: o.client.name },
        country: o.change.country,
        regulatoryArea: mapArea((o.change.affectedAreas as string[])[0] ?? 'regulatory'),
        obligationId: o.id,
        regulatoryChangeId: o.changeId,
        status: mapObligationStatus(o.status, dateStr),
        assignedTo: o.assignedTo || null,
        notes: null,
        autoGenerated: true,
        previousDate: null,
        updateReason: null,
      };
    });

    res.json({ data: events, total: events.length });
  });

  // -----------------------------------------------------------------------
  // GET /calendar/summary — KPI counts from real data
  // -----------------------------------------------------------------------
  router.get('/calendar/summary', async (_req: Request, res: Response) => {
    const obligations = await deps.prisma.obligation.findMany({
      where: { status: { not: 'COMPLETED' } },
      include: {
        change: { select: { country: true } },
      },
    });

    const now = todayStr();
    const weekEnd = dateOffset(7);
    const monthEnd = dateOffset(30);

    const events = obligations.map((o) => ({
      date: o.deadline.toISOString().split('T')[0]!,
      country: o.change.country,
      type: 'DEADLINE' as CalendarEventType,
    }));

    const overdue = events.filter((e) => e.date < now).length;
    const dueThisWeek = events.filter((e) => e.date >= now && e.date <= weekEnd).length;
    const dueThisMonth = events.filter((e) => e.date >= now && e.date <= monthEnd).length;

    const countryMap = new Map<string, number>();
    for (const e of events) countryMap.set(e.country, (countryMap.get(e.country) ?? 0) + 1);
    const byCountry = Array.from(countryMap.entries()).map(([country, count]) => ({ country, count }));

    const typeMap = new Map<CalendarEventType, number>();
    for (const e of events) typeMap.set(e.type, (typeMap.get(e.type) ?? 0) + 1);
    const byType = Array.from(typeMap.entries()).map(([type, count]) => ({ type, count }));

    const summary: CalendarSummary = { overdue, dueThisWeek, dueThisMonth, byCountry, byType };
    res.json(summary);
  });

  // -----------------------------------------------------------------------
  // POST /calendar/events — create manual event (stores as obligation)
  // -----------------------------------------------------------------------
  router.post('/calendar/events', async (req: Request, res: Response) => {
    const requestId = req.requestId ?? randomUUID();
    const body = req.body;

    if (!body.title || !body.date) {
      throw Errors.validation(requestId, [{ path: ['title', 'date'], message: 'Required fields' }]);
    }

    // For manual events, we need a client and change reference
    // Use the first available client/change as fallback
    const client = body.clientId
      ? await deps.prisma.client.findUnique({ where: { id: body.clientId } })
      : await deps.prisma.client.findFirst();
    const change = await deps.prisma.regulatoryChange.findFirst();

    if (!client || !change) {
      throw Errors.validation(requestId, [{ path: ['clientId'], message: 'No clients or regulations found in DB' }]);
    }

    const obligation = await deps.prisma.obligation.create({
      data: {
        clientId: client.id,
        tenantId: client.tenantId,
        changeId: change.id,
        title: body.title,
        description: body.notes ?? '',
        deadline: new Date(body.date),
        status: 'PENDING',
        priority: 'MEDIUM',
        assignedTo: body.assignedTo ?? '',
      },
    });

    const dateStr = obligation.deadline.toISOString().split('T')[0]!;
    const event: CalendarEvent = {
      id: obligation.id,
      type: (body.type as CalendarEventType) ?? 'DEADLINE',
      title: obligation.title,
      date: dateStr,
      daysUntil: daysUntilDate(dateStr),
      client: { id: client.id, name: client.name },
      country: body.country ?? change.country,
      regulatoryArea: body.regulatoryArea ?? 'general',
      obligationId: obligation.id,
      regulatoryChangeId: change.id,
      status: 'PENDING',
      assignedTo: body.assignedTo ?? null,
      notes: body.notes ?? null,
      autoGenerated: false,
      previousDate: null,
      updateReason: null,
    };

    logger.info({ operation: 'calendar:create', requestId, eventId: event.id, result: 'success' });
    res.status(201).json(event);
  });

  // -----------------------------------------------------------------------
  // PATCH /calendar/events/:id — update obligation status
  // -----------------------------------------------------------------------
  router.patch('/calendar/events/:id', async (req: Request, res: Response) => {
    const requestId = req.requestId ?? randomUUID();
    const { id } = req.params;
    const body = req.body;

    const obligation = await deps.prisma.obligation.findUnique({
      where: { id },
      include: {
        client: { select: { id: true, name: true } },
        change: { select: { country: true, affectedAreas: true } },
      },
    });
    if (!obligation) throw Errors.notFound(requestId, 'CalendarEvent', id!);

    const data: Record<string, unknown> = {};
    if (body.status) data['status'] = body.status;
    if (body.assignedTo !== undefined) data['assignedTo'] = body.assignedTo;
    if (body.date) data['deadline'] = new Date(body.date);

    const updated = await deps.prisma.obligation.update({ where: { id }, data });
    const dateStr = updated.deadline.toISOString().split('T')[0]!;

    const event: CalendarEvent = {
      id: updated.id,
      type: 'DEADLINE',
      title: updated.title,
      date: dateStr,
      daysUntil: daysUntilDate(dateStr),
      client: { id: obligation.client.id, name: obligation.client.name },
      country: obligation.change.country,
      regulatoryArea: mapArea((obligation.change.affectedAreas as string[])[0] ?? 'regulatory'),
      obligationId: updated.id,
      regulatoryChangeId: obligation.changeId,
      status: mapObligationStatus(updated.status, dateStr),
      assignedTo: updated.assignedTo || null,
      notes: body.notes ?? null,
      autoGenerated: true,
      previousDate: body.date && obligation.deadline.toISOString().split('T')[0] !== body.date
        ? obligation.deadline.toISOString().split('T')[0]!
        : null,
      updateReason: body.updateReason ?? null,
    };

    logger.info({ operation: 'calendar:update', requestId, eventId: event.id, result: 'success' });
    res.json(event);
  });

  // -----------------------------------------------------------------------
  // GET /calendar/export/ical — iCal file from real data
  // -----------------------------------------------------------------------
  router.get('/calendar/export/ical', async (req: Request, res: Response) => {
    const from = req.query['from'] as string | undefined;
    const to = req.query['to'] as string | undefined;
    const clientId = req.query['clientId'] as string | undefined;

    const where: Record<string, unknown> = {};
    if (clientId) where['clientId'] = clientId;
    if (from || to) {
      const df: Record<string, Date> = {};
      if (from) df['gte'] = new Date(from);
      if (to) df['lte'] = new Date(to);
      where['deadline'] = df;
    }

    const obligations = await deps.prisma.obligation.findMany({
      where,
      include: {
        client: { select: { name: true } },
        change: { select: { country: true } },
      },
      orderBy: { deadline: 'asc' },
    });

    const lines: string[] = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Grant Thornton//RegWatch AI//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:RegWatch AI — Compliance Calendar',
    ];

    for (const o of obligations) {
      const dtStart = o.deadline.toISOString().split('T')[0]!.replace(/-/g, '');
      lines.push(
        'BEGIN:VEVENT',
        `UID:${o.id}@regwatch.grantthornton.com`,
        `DTSTART;VALUE=DATE:${dtStart}`,
        `SUMMARY:${o.title}`,
        `DESCRIPTION:Cliente: ${o.client.name}\\nPais: ${o.change.country}\\nEstado: ${o.status}\\nPrioridad: ${o.priority}`,
        'CATEGORIES:DEADLINE',
        'BEGIN:VALARM', 'TRIGGER:-P7D', 'ACTION:DISPLAY', `DESCRIPTION:7 dias para: ${o.title}`, 'END:VALARM',
        'BEGIN:VALARM', 'TRIGGER:-P1D', 'ACTION:DISPLAY', `DESCRIPTION:Manana: ${o.title}`, 'END:VALARM',
        'END:VEVENT',
      );
    }

    lines.push('END:VCALENDAR');

    res.setHeader('Content-Type', 'text/calendar; charset=utf-8');
    res.setHeader('Content-Disposition', 'attachment; filename="regwatch-calendar.ics"');
    res.send(lines.join('\r\n'));
  });

  return router;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function todayStr(): string {
  return new Date().toISOString().split('T')[0]!;
}

function dateOffset(days: number): string {
  return new Date(Date.now() + days * 86_400_000).toISOString().split('T')[0]!;
}

function daysUntilDate(dateStr: string): number {
  const target = new Date(dateStr).getTime();
  const now = new Date(todayStr()).getTime();
  return Math.ceil((target - now) / 86_400_000);
}

function mapObligationStatus(status: string, dateStr: string): CalendarEventStatus {
  if (status === 'COMPLETED') return 'COMPLETED';
  if (status === 'IN_PROGRESS') return 'IN_PROGRESS';
  if (status === 'OVERDUE' || dateStr < todayStr()) return 'OVERDUE';
  return 'PENDING';
}

function mapArea(area: string): string {
  const mapping: Record<string, string> = {
    'securities': 'Financiero', 'banking': 'Financiero', 'digital-finance': 'Financiero',
    'corporate': 'Financiero', 'insurance': 'Financiero', 'disclosure': 'Financiero',
    'data-protection': 'Datos/GDPR',
    'labor': 'Laboral',
    'environmental': 'Ambiental', 'climate': 'Ambiental', 'energy': 'Ambiental',
    'fiscal': 'Fiscal', 'international-tax': 'Fiscal',
    'sustainability': 'Sostenibilidad',
    'aml': 'Financiero', 'compliance': 'Financiero',
  };
  return mapping[area] ?? area;
}
