// ============================================================================
// FILE: apps/api/src/monitoring/dashboard.ts
// Application Insights dashboard definition and alert rules.
// Export as JSON for ARM template or Bicep deployment.
// ============================================================================

/**
 * Kusto queries for Application Insights dashboard tiles.
 * Use these in Azure Portal → Application Insights → Workbooks.
 */
export const DASHBOARD_QUERIES = {
  /** Documents ingested in the last 24 hours by source. */
  documentsIngested24h: `
    customMetrics
    | where name == "documents_ingested"
    | where timestamp > ago(24h)
    | summarize total = sum(value) by tostring(customDimensions.source)
    | order by total desc
  `,

  /** Alerts generated by severity in the last 7 days. */
  alertsBySeverity7d: `
    customMetrics
    | where name == "alerts_generated"
    | where timestamp > ago(7d)
    | summarize total = sum(value) by tostring(customDimensions.severity)
    | order by total desc
  `,

  /** RAG latency p95 over time (1-hour buckets). */
  ragLatencyP95: `
    customMetrics
    | where name == "rag_latency_ms.p95"
    | where timestamp > ago(24h)
    | summarize p95 = avg(value) by bin(timestamp, 1h)
    | order by timestamp asc
  `,

  /** Cache hit rate over time. */
  cacheHitRate: `
    customMetrics
    | where name == "cache_hit_rate"
    | where timestamp > ago(24h)
    | summarize rate = avg(value) by bin(timestamp, 1h)
    | order by timestamp asc
  `,

  /** HITL pending alerts gauge. */
  hitlPending: `
    customMetrics
    | where name == "hitl_pending"
    | where timestamp > ago(1h)
    | summarize current = max(value)
  `,

  /** RAG query results breakdown. */
  ragQueryResults: `
    customMetrics
    | where name == "rag_queries"
    | where timestamp > ago(24h)
    | summarize total = sum(value) by tostring(customDimensions.result)
  `,

  /** Error rate (5xx responses). */
  errorRate: `
    requests
    | where timestamp > ago(1h)
    | summarize total = count(), errors = countif(resultCode >= 500)
    | extend error_rate = round(100.0 * errors / total, 2)
  `,
} as const;

/**
 * Alert rules for Application Insights.
 * Deploy via Bicep or ARM template.
 */
export const ALERT_RULES = [
  {
    name: 'rag-latency-high',
    description: 'RAG latency p95 exceeds 5000ms',
    severity: 2, // Warning
    query: `
      customMetrics
      | where name == "rag_latency_ms.p95"
      | where timestamp > ago(15m)
      | summarize p95 = avg(value)
      | where p95 > 5000
    `,
    frequency: '15m',
    windowSize: '15m',
    actionGroupName: 'regwatch-oncall',
  },
  {
    name: 'hitl-backlog-high',
    description: 'More than 10 HIGH alerts pending human review',
    severity: 2,
    query: `
      customMetrics
      | where name == "hitl_pending"
      | where timestamp > ago(5m)
      | summarize current = max(value)
      | where current > 10
    `,
    frequency: '5m',
    windowSize: '5m',
    actionGroupName: 'regwatch-oncall',
  },
  {
    name: 'ingestion-failure',
    description: 'Ingestion job failed for any source',
    severity: 1, // Critical
    query: `
      customEvents
      | where name == "ingestion:job_failed"
      | where timestamp > ago(30m)
      | count
      | where Count > 0
    `,
    frequency: '15m',
    windowSize: '30m',
    actionGroupName: 'regwatch-oncall',
  },
  {
    name: 'error-rate-spike',
    description: 'API error rate exceeds 5% in 5-minute window',
    severity: 1,
    query: `
      requests
      | where timestamp > ago(5m)
      | summarize total = count(), errors = countif(resultCode >= 500)
      | extend error_pct = 100.0 * errors / total
      | where error_pct > 5 and total > 10
    `,
    frequency: '5m',
    windowSize: '5m',
    actionGroupName: 'regwatch-oncall',
  },
] as const;
